Order items statuses
dawiddworak88/Giuru pull request #104
Opened 2022-06-28 07:24 UTC by SebaKas21

Hi @dawiddworak88 

Now i must try integrate with profit

2022-08-15 17:10 UTC, dawiddworak88 requested changes
Let's remember to create smaller PRs for tasks in the future (split tasks in subtasks like FE, API, BE, start with Buyer.Web, then another PR for Seller.Web, etc.)

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/Infrastructure/Orders/Entities/OrderComment.cs
> -﻿using Foundation.GenericRepository.Entities;
**suggestion:** Let's revert it. We're going to need it.

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/Infrastructure/Orders/Entities/OrderItemStatusChange.cs
> +        public string OrderItemStatusChangeComment { get; set; }
**suggestion:** you'll never know what language the comment has been entered in. Please change it to and add a corresponding translation entity:

public virtual OrderItemStatusChangeCommentTranslation OrderItemStatusChangeCommentTranslation { get; set; }

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/Services/OrdersService.cs
> +                    OrderItemStateId = OrderStatesConstants.NewId,
**suggestion:** Introduce new constants for order items: OrderItemStatesConstants and OrderItemStatusConstants

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/Services/OrdersService.cs
> +            foreach (var orderedItem in orderedItems.OrEmptyIfNull().ToList())
**question:** is it possible to avoid ToList() here?

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/Services/OrdersService.cs
> +            }*/
**suggestion:** let's get rid of this block or fix it. We have a source control to track it.

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/ServicesModels/GetOrderItemStatusesHistoryServiceModel.cs
> +    public class GetOrderItemStatusesHistoryServiceModel : BaseServiceModel
**suggestion:** either rename OrderItemStatusChange to OrderItemStatusHistory or GetOrderItemStatusesHistoryServiceModel to GetOrderItemStatusChangesServiceModel (and all other)

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/ServicesModels/OrderItemServiceModel.cs
> +        public Guid OrderStatusId { get; set; }
**suggestion:** rename to OrderItemStatusId

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/ServicesModels/OrderItemServiceModel.cs
> +        public Guid OrderStateId { get; set; }
**suggestion:** rename to OrderItemStateId

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/ServicesModels/OrderItemServiceModel.cs
> +        public string OrderStatusComment { get; set; }
**suggestion:** rename to OrderItemStatusChangeComment

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/ServicesModels/OrderItemStatusesHistoryItemServiceModel.cs
> +        public Guid OrderStateId { get; set; }
**suggestion:** the same everywhere - rename to Order**Item**StatusId, etc.

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/ServicesModels/UpdateOrderItemsStatusServiceModel.cs
> +        public int OrderItemIndex { get; set; }
**suggestion:** there is something wrong. There should be no OrderItemIndex and IsDone because they aren't related strictly to the B2B platform.

2022-08-15 17:10 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/v1/RequestModels/OrderItemStatusCommentRequestModel.cs
> +        public string OrderItemStatusComment { get; set; }
**suggestion:** there are language params missing everywhere. You'll never know what language the comment has been provided in.

2022-08-16 11:15 UTC, SebaKas21 commented on be/src/Project/Services/Ordering/Ordering.Api/Infrastructure/Orders/Entities/OrderComment.cs
> -﻿using Foundation.GenericRepository.Entities;
Okay, can you describe for what?

2022-08-16 11:40 UTC, SebaKas21 commented on be/src/Project/Services/Ordering/Ordering.Api/Services/OrdersService.cs
> +            foreach (var orderedItem in orderedItems.OrEmptyIfNull().ToList())
WIthout ToList(), we receive in console: "connection to sql must be first closed", but with ToList() work without additional problems

2022-08-16 11:43 UTC, SebaKas21 commented on be/src/Project/Services/Ordering/Ordering.Api/ServicesModels/UpdateOrderItemsStatusServiceModel.cs
> +        public int OrderItemIndex { get; set; }
It is for updating order items from ordering-sync, delete this endpoint?

2022-08-17 09:26 UTC, SebaKas21 commented
Hi @dawiddworak88 

You can look now :)

2022-09-14 11:01 UTC, dawiddworak88 requested changes

2022-09-14 11:01 UTC, dawiddworak88 commented on fe/src/shared/components/OrderItemStatusChanges/OrderItemStatusChanges.js
> +                                        <TableCell>{isMounted ? moment.utc(statusChange.createdDate).local().format("L LT") : moment.utc(statusChange.createdDate).format("L LT")}</TableCell>
**suggestion:** use check for window object

2022-09-14 11:01 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/shared/constants/OrderConstants.js
> +        return "578480b3-15ef-492d-9f86-9827789c6804";
**suggestion:** avoid hard-coding backend guids

2022-09-14 11:01 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Orders/components/OrderItemForm/OrderItemForm.js
> +    const [isSended, setIsSended] = useState(false);
**suggestion (non-blocking):** isSent

2022-09-14 11:01 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Orders/components/OrderItemForm/OrderItemForm.js
> +                            <img src={props.imageUrl} alt=""/>
**suggestion:** provide alt value

2022-10-05 18:09 UTC, dawiddworak88 requested changes
Hi @SebaKas21 ,

at the moment there are following warnings and errors for existing order items when I try to access them. Could you please fix them one by one?

Warning: Failed prop type: Invalid prop `outletQuantity` of type `number` supplied to `OrderItemForm`, expected `string`.
    at OrderItemForm (webpack://aspnetcore-react-ssr/./src/project/Seller.Portal/areas/Orders/components/OrderItemForm/OrderItemForm.js?:37:78)
    at OrderItemPage (webpack://aspnetcore-react-ssr/./src/project/Seller.Portal/areas/Orders/pages/OrderItemPage/OrderItemPage.js?:29:102)
printWarning @ react.development.js:208
error @ react.development.js:182
checkPropTypes @ react.development.js:2073
validatePropTypes @ react.development.js:2274
createElementWithValidation @ react.development.js:2378
OrderItemPage @ OrderItemPage.js:66
renderWithHooks @ react-dom.development.js:16175
mountIndeterminateComponent @ react-dom.development.js:20908
beginWork @ react-dom.development.js:22411
beginWork$1 @ react-dom.development.js:27376
performUnitOfWork @ react-dom.development.js:26511
workLoopSync @ react-dom.development.js:26417
renderRootSync @ react-dom.development.js:26385
performConcurrentWorkOnRoot @ react-dom.development.js:25689
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:86 Warning: Expected server HTML to contain a matching <div> in <div>.
    at div
    at eval (webpack://aspnetcore-react-ssr/./node_modules/react-toastify/dist/react-toastify.esm.js?:18:15999)
    at InnerThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js?:23:70)
    at ThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js?:49:5)
    at ThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js?:43:5)
    at OrderItemPage (webpack://aspnetcore-react-ssr/./src/project/Seller.Portal/areas/Orders/pages/OrderItemPage/OrderItemPage.js?:29:102)
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnForInsertedHydratedElement @ react-dom.development.js:10496
didNotFindHydratableInstanceWithinContainer @ react-dom.development.js:11400
warnNonhydratedInstance @ react-dom.development.js:14242
tryToClaimNextHydratableInstance @ react-dom.development.js:14415
updateHostComponent$1 @ react-dom.development.js:20706
beginWork @ react-dom.development.js:22442
beginWork$1 @ react-dom.development.js:27376
performUnitOfWork @ react-dom.development.js:26511
workLoopSync @ react-dom.development.js:26417
renderRootSync @ react-dom.development.js:26385
performConcurrentWorkOnRoot @ react-dom.development.js:25689
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
3react-dom.development.js:14388 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:14388:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:14416:7)
    at updateHostComponent$1 (react-dom.development.js:20706:5)
    at beginWork (react-dom.development.js:22442:14)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:16)
    at invokeGuardedCallback (react-dom.development.js:4274:31)
    at beginWork$1 (react-dom.development.js:27400:7)
    at performUnitOfWork (react-dom.development.js:26511:12)
    at workLoopSync (react-dom.development.js:26417:5)
throwOnHydrationMismatch @ react-dom.development.js:14388
tryToClaimNextHydratableInstance @ react-dom.development.js:14416
updateHostComponent$1 @ react-dom.development.js:20706
beginWork @ react-dom.development.js:22442
callCallback @ react-dom.development.js:4161
invokeGuardedCallbackDev @ react-dom.development.js:4210
invokeGuardedCallback @ react-dom.development.js:4274
beginWork$1 @ react-dom.development.js:27400
performUnitOfWork @ react-dom.development.js:26511
workLoopSync @ react-dom.development.js:26417
renderRootSync @ react-dom.development.js:26385
performConcurrentWorkOnRoot @ react-dom.development.js:25689
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:208 Warning: Failed prop type: The prop `onChange` is marked as required in `ForwardRef(DatePicker)`, but its value is `undefined`.
    at DatePicker (webpack://aspnetcore-react-ssr/./node_modules/@mui/lab/node_modules/@mui/x-date-pickers/DatePicker/DatePicker.js?:39:81)
    at OrderItemForm (webpack://aspnetcore-react-ssr/./src/project/Seller.Portal/areas/Orders/components/OrderItemForm/OrderItemForm.js?:37:78)
    at Store (webpack://aspnetcore-react-ssr/./src/shared/stores/Store.js?:19:5)
    at InnerThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js?:23:70)
    at ThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js?:49:5)
    at ThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js?:43:5)
    at OrderItemPage (webpack://aspnetcore-react-ssr/./src/project/Seller.Portal/areas/Orders/pages/OrderItemPage/OrderItemPage.js?:29:102)
printWarning @ react.development.js:208
error @ react.development.js:182
checkPropTypes @ react.development.js:2073
validatePropTypes @ react.development.js:2274
createElementWithValidation @ react.development.js:2378
OrderItemForm @ OrderItemForm.js:346
renderWithHooks @ react-dom.development.js:16175
mountIndeterminateComponent @ react-dom.development.js:20908
beginWork @ react-dom.development.js:22411
beginWork$1 @ react-dom.development.js:27376
performUnitOfWork @ react-dom.development.js:26511
workLoopSync @ react-dom.development.js:26417
renderRootSync @ react-dom.development.js:26385
performConcurrentWorkOnRoot @ react-dom.development.js:25689
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:208 Warning: Failed prop type: The prop `labels` is marked as required in `OrderItemStatusChanges`, but its value is `null`.
    at OrderItemStatusChanges (webpack://aspnetcore-react-ssr/./src/shared/components/OrderItemStatusChanges/OrderItemStatusChanges.js?:27:5)
    at OrderItemForm (webpack://aspnetcore-react-ssr/./src/project/Seller.Portal/areas/Orders/components/OrderItemForm/OrderItemForm.js?:37:78)
    at Store (webpack://aspnetcore-react-ssr/./src/shared/stores/Store.js?:19:5)
    at InnerThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js?:23:70)
    at ThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js?:49:5)
    at ThemeProvider (webpack://aspnetcore-react-ssr/./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js?:43:5)
    at OrderItemPage (webpack://aspnetcore-react-ssr/./src/project/Seller.Portal/areas/Orders/pages/OrderItemPage/OrderItemPage.js?:29:102)
printWarning @ react.development.js:208
error @ react.development.js:182
checkPropTypes @ react.development.js:2073
validatePropTypes @ react.development.js:2274
createElementWithValidation @ react.development.js:2378
OrderItemForm @ OrderItemForm.js:516
renderWithHooks @ react-dom.development.js:16175
mountIndeterminateComponent @ react-dom.development.js:20908
beginWork @ react-dom.development.js:22411
beginWork$1 @ react-dom.development.js:27376
performUnitOfWork @ react-dom.development.js:26511
workLoopSync @ react-dom.development.js:26417
renderRootSync @ react-dom.development.js:26385
performConcurrentWorkOnRoot @ react-dom.development.js:25689
workLoop  [...]

2022-10-05 18:09 UTC, dawiddworak88 commented on fe/src/shared/components/OrderItemStatusChanges/OrderItemStatusChanges.js
> +    const { labels, statusChanges } = props;
**suggestion (non-blocking):** statusChanges here are redundant because below props.statusChanges are used

2022-10-05 18:09 UTC, dawiddworak88 commented on fe/src/shared/components/OrderItemStatusChanges/OrderItemStatusChanges.js
> +    statusChanges: PropTypes.array.isRequired
**suggestion:** isRequired is probably redundant here because for many existing orders there can be no status changes

2022-10-05 18:09 UTC, dawiddworak88 commented on fe/src/shared/components/OrderItemStatusChanges/OrderItemStatusChanges.js
> +                <h3 className="title is-4">{labels.title}</h3>
**suggestion:** this line throws an error because labels are null for existing order items

2022-10-10 17:09 UTC, dawiddworak88 approved these changes

2022-10-10 17:10 UTC, merged