Added QRCode dialog for catalog component
dawiddworak88/Giuru pull request #122
Opened 2022-09-09 12:23 UTC by SebaKas21

Hi @dawiddworak88 

If you have any comments then:
I had to add a link in the download center with and without cdn, so as not to use it: D

There is null, but without it we won't get a thumbnail, anyway take a look :)

2022-09-09 19:01 UTC, SebaKas21 commented
Hi

I couldn't wait to add these fixes because I wanted everything to work in production  :D

2022-09-11 20:43 UTC, dawiddworak88 requested changes
Hi @SebaKas21 ,

I've rebuilt FE but I couldn't see the qr button anywhere. Could you please have a look at it?

![image](https://user-images.githubusercontent.com/7514974/189548111-a255a62d-4a28-490f-93c3-a0f0190b1e09.png)

Cheers,
Dawid

2022-09-12 05:22 UTC, SebaKas21 commented
Hi @dawiddworak88

 I have, without re-build

![obraz](https://user-images.githubusercontent.com/93117743/189579208-22fe0fb3-32a7-4dcf-aa8b-86430aa6d29b.png)

2022-09-12 18:59 UTC, dawiddworak88 approved these changes

2022-09-12 18:59 UTC, merged