Analytics dashboard api
dawiddworak88/Giuru pull request #153
Opened 2022-10-17 13:20 UTC by SebaKas21

Hi @dawiddworak88 

I was thinking to create two endopoints. The first is for displaying the top 10 products and the second is for the chart.

Check this out.

2022-11-08 12:30 UTC, SebaKas21 commented
Hi @dawiddworak88 

You can make review :D

2022-11-27 19:07 UTC, dawiddworak88 commented
Hi @SebaKas21 , could you please merge develop to the branch and add open telemetry?

2022-12-02 21:29 UTC, dawiddworak88 requested changes

2022-12-02 21:29 UTC, dawiddworak88 commented on be/src/Project/Services/Analytics/Analytics.Api/v1/Controllers/SalesAnalyticsController.cs
> +                    Country = x.Country,
**suggestion:** let's merge the develop branch to this one. Let's use country id and introduce the dimension country with translation for name.

2022-12-05 19:21 UTC, dawiddworak88 approved these changes
Looks good, let's develop on the top of it 🌞

2022-12-05 19:21 UTC, merged