Role groups for entities
dawiddworak88/Giuru pull request #179
Opened 2022-11-05 19:37 UTC by SebaKas21

Hi @dawiddworak88 

I added missed PR with role groups

2022-11-09 18:34 UTC, dawiddworak88 requested changes

2022-11-09 18:34 UTC, dawiddworak88 commented on be/src/Project/Services/News/News.Api/Services/News/NewsService.cs
> +            foreach (var groupId in model.GroupIds.OrEmptyIfNull())
**suggestion:** please replace group with clientGroup everywhere. clientGroupId instead of groupId, ClientGroupIds instead of GroupIds, etc.

2022-12-15 18:41 UTC, dawiddworak88 commented
Hi @SebaKas21, would you solve the merge conflicts and the role groups? I'd merge it.

2022-12-27 08:46 UTC, SebaKas21 commented
Hi @dawiddworak88 

Merge conflicts are resolved

2023-04-10 16:49 UTC, dawiddworak88 commented
Hi @SebaKas21 , let's merge it. If you could resolve the merge conflicts, we'd finally merge it and forget about it :)

2023-04-11 12:25 UTC, SebaKas21 commented
Hi @dawiddworak88,

I think that we should check this one more time

2025-01-26 09:30 UTC, dawiddworak88 commented
Let's leave it for now. We'll come back to the topic in the future

2025-01-26 09:30 UTC, closed without merging