Issue/countries chart date range
dawiddworak88/Giuru pull request #263
Opened 2023-02-26 23:50 UTC by SebaKas21

Hi @dawiddworak88 

I know how to transfer data from fe to the controller in the web. Thanks, but the problem is elsewhere. 

Exactly the problem is that the ApiClientService and the GetAsync method converts the date to a different format.
Date transferred to Repository: 2023.02.27 00:48
Date transferred from Repository to Api: 02.27.2023 00:48

URL going to analytics-api: http://analytics-api/api/v1/salesanalytics/countries?FromDate=26.11.2022+23%3a40%3a10&ToDate=26.02.2023+23%3a40%3a10

Response is: Bad Request

2023-02-27 20:10 UTC, dawiddworak88 requested changes
Hi @SebaKas21, I adjusted the date time handling in ApiClient Service. I'd rather not create a PR yet because it still needs a lot of work and code clean up: 

![image](https://user-images.githubusercontent.com/7514974/221672356-aaf70397-2dc6-47cc-946a-fd90ee128157.png)

2023-02-28 07:39 UTC, SebaKas21 commented
Hi @dawiddworak88  

I know, but I wanted to show you the problem that was occurring.

Thank you very much for your help ;)

2023-03-01 10:18 UTC, SebaKas21 commented
Hi @dawiddworak88 

You haven't published your review

2023-03-02 11:55 UTC, SebaKas21 commented
Hi @dawiddworak88 

I think you can take a look at it now :)

2023-03-06 11:33 UTC, dawiddworak88 approved these changes

2023-03-06 11:33 UTC, dawiddworak88 commented on be/src/Project/Services/Analytics/Analytics.Api/Validators/GetAnnualSalesModelValidator.cs
> +                if ((y.FromDate > currentDate) && (y.ToDate > currentDate))
**suggestion:** delete '&& (y.ToDate > currentDate)'

2023-03-06 11:33 UTC, dawiddworak88 commented on be/src/Project/Services/Analytics/Analytics.Api/Validators/GetAnnualSalesModelValidator.cs
> +                if (y.FromDate > y.ToDate)
**suggestion:** put it all in once condition

2023-03-06 11:33 UTC, dawiddworak88 commented on be/src/Project/Services/Analytics/Analytics.Api/Validators/GetDailySalesModelValidator.cs
> +            this.RuleFor(x => x).Must(y =>
**suggestion:** add inheritance not to repeat code

2023-03-06 11:33 UTC, dawiddworak88 commented on be/src/Project/Services/Analytics/Analytics.Api/Validators/GetAnnualSalesModelValidator.cs
> +                if (y.FromDate > y.ToDate)
**suggestion:** add check if fromDate or toDate is not null, empty, zeros or DateTime.MinDate

2023-03-06 11:33 UTC, dawiddworak88 commented on be/src/Project/Services/Analytics/Analytics.Api/v1/Controllers/SalesAnalyticsController.cs
> +        public IActionResult GetDailySales(DateTime fromDate, DateTime toDate)
**suggestion:** make them nullable and set a default value of toDate to UtcNow If null

2023-03-06 11:33 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Dashboard/ApiControllers/DailySalesAnalyticsApiController.cs
> +                    if (dailySalesItem.Month < 10)
**suggestion:** move to constants and add descriptive name

2023-03-06 11:33 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Dashboard/ModelBuilders/DailySalesAnalyticsModelBuilder.cs
> +            var fromDate = DateTime.UtcNow.AddDays(-21);
**suggestion:** remove magic strings from code

2023-03-06 11:33 UTC, merged