Product card
dawiddworak88/Giuru pull request #264
Opened 2023-03-06 10:01 UTC by SebaKas21

2023-03-24 07:34 UTC, dawiddworak88 commented
Hi @SebaKas21 , would you remove the conflicts here?

2023-03-25 18:16 UTC, dawiddworak88 requested changes

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/GlobalResources.en.resx
> +    <value>Definicja</value>
**suggestion:** Definition

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/ProductResources.de.resx
> +    <value>NeuerGegenstand</value>
**suggestion:** Neuer Gegenstand

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/ProductResources.en.resx
> +    <value>Add new product card</value>
**suggestion:** Add a new product card

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/ProductResources.pl.resx
> +    <value>NowyElement</value>
**suggestion:** Nowy element

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/Controllers/CategoriesController.cs
> +            Console.WriteLine("TEEEEESTYY");
**suggestion:** :)

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/Controllers/ProductCardController.cs
> +        private readonly IAsyncComponentModelBuilder<ComponentModelBase, ProductCardPageViewModel> productCardPageModelBuilder;
**suggestion:** _productCardPageModelBuilder

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/Controllers/ProductCardController.cs
> +                IsAuthenticated = this.User.Identity.IsAuthenticated,
**suggestion:** this redundant

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/Controllers/ProductCardController.cs
> +            var viewModel = await this.productCardPageModelBuilder.BuildModelAsync(componentModel);
**suggestion (non-blocking):** _productCardPageModelBuilder

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/Controllers/ProductCardsController.cs
> +        private readonly IAsyncComponentModelBuilder<ComponentModelBase, ProductCardsPageViewModel> productCardsPageModelBuilder;
**suggestion:** _productCardsPageModelBuilder

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/Controllers/ProductCardsController.cs
> +            this.productCardsPageModelBuilder = productCardsPageModelBuilder;
**suggestion:** this redundant

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ModelBuilders/ProductCardPageModelBuilder.cs
> +            this.headerModelBuilder = headerModelBuilder;
**suggestion:** this redundant

2023-03-25 18:16 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ModelBuilders/ProductCardPageModelBuilder.cs
> +        private readonly IAsyncComponentModelBuilder<ComponentModelBase, SellerHeaderViewModel> headerModelBuilder;
**suggestion:** _headerModelBuilder

2023-03-25 18:16 UTC, dawiddworak88 commented on fe/projects/Seller.Portal/src/areas/Products/components/ProductCardForm/ProductCardForm.js
> +                delete newDefinitions[element.definitionId];
**suggestion:** delete is dangerous, wouldn't we be able to use immutable technique to do it

2023-03-25 18:16 UTC, dawiddworak88 commented on fe/projects/Seller.Portal/src/areas/Products/components/ProductCardModal/ProductCardModal.js
> +                NavigationHelper.redirect(currentDefinition.url, "_blank");
**suggestion:** I'd create a new function in NavigationHelper.openInNewTab

2023-03-25 18:16 UTC, dawiddworak88 commented on fe/projects/Seller.Portal/src/areas/Products/components/ProductCardModal/ProductCardModal.js
> +        const format = new RegExp(/(.|\s)*\S(.|\s)*/)
**suggestion:** Let's move it to constants and add a descriptive name what this regex represents

2023-04-10 16:46 UTC, dawiddworak88 commented
Hi @SebaKas21, if you could resolve the conflicts and test it in detail once again, we'd merge it and deploy to production.

2023-04-13 13:12 UTC, SebaKas21 commented
Hi @dawiddworak88 

I added minor corrections, thanks to which I eliminated errors and the product card now works properly

2023-04-15 18:52 UTC, dawiddworak88 approved these changes
Thank you @SebaKas21, let's go for it

2023-04-15 18:53 UTC, merged