Fixed displaying available quantity on sidebar
dawiddworak88/Giuru pull request #271
Opened 2023-03-21 14:16 UTC by SebaKas21

2023-03-22 07:42 UTC, dawiddworak88 requested changes

2023-03-22 07:42 UTC, dawiddworak88 commented on fe/src/project/AspNetCore/shared/components/Sidebar/Sidebar.js
> +                                                        {carouselItem.availableQuantity > 0 && carouselItem.availableQuantity &&
**suggestion (to check):** looks redundant

2023-03-24 07:33 UTC, dawiddworak88 commented
Hi @SebaKas21, would you check it and make it as a hotfix? I'd deploy it first today.

2023-03-24 08:32 UTC, SebaKas21 commented
@dawiddworak88 

Okay

2023-03-24 08:40 UTC, SebaKas21 commented
i created branch hotfix so i close PR

2023-03-24 08:40 UTC, closed without merging