Redesigned footer
dawiddworak88/Giuru pull request #280
Opened 2023-06-25 23:39 UTC by SebaKas21

Hi @dawiddworak88,

Footer has been redesigned according to the design in figma

2023-07-03 19:03 UTC, dawiddworak88 requested changes

2023-07-03 19:03 UTC, dawiddworak88 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/GlobalResources.de.resx
> +    <value>© [year] | ELTAP Spółka z ograniczoną odpowiedzialnością Sp.k. Alle Rechte vorbehalten.</value>
**suggestion:** lets' move these texts to Content.API because when I deploy it to other tenant the text is going to be invalid

2023-07-04 00:13 UTC, SebaKas21 commented
Everything has been corrected

2023-08-06 10:20 UTC, dawiddworak88 requested changes

2023-08-06 10:20 UTC, dawiddworak88 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/GlobalResources.de.resx
> +    <value>© [year] | ELTAP Spółka z ograniczoną odpowiedzialnością Sp.k. Alle Rechte vorbehalten.</value>
**suggestion:** Hi @SebaKas21, there is 'ELTAP' hardcoded. The place of this text is either in the content API. In my view the easiest will be to revert the previous version

2023-08-06 10:59 UTC, dawiddworak88 commented
@SebaKas21, here it's also important to add the required content API postgres SQL scripts to the init script. Upon first checkout and project run the footer should be present and look nice

2023-10-12 06:18 UTC, dawiddworak88 approved these changes
Thank you

2023-10-12 11:11 UTC, merged