Product gallery on detail page
dawiddworak88/Giuru pull request #281
Opened 2023-08-04 10:56 UTC by PiotrZaranek

2023-08-04 11:49 UTC, SebaKas21 requested changes

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/package.json
> +    "swiper": "^9.2.0",
**suggestion:** Please remove ^

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +
**suggestion (non-blocking):** Redundant empty lines

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +    const [fabricsSliderOnEnd, setFabricsSliderOnEnd] = useState(false);
**suggestion:** Is never used. if you want use, please change fabricsSliderOnEnd to meanfuling name for product detail (not fabrics)

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +    const [fabricsSliderOnStart, setFabricsSliderOnStart] = useState(true);
**suggestion:** Is never used. if you want use, please change fabricsSliderOnStart to meanfuling name for product detail (not fabrics)

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
**suggestion (non-blocking):** redundant empty line

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +    }, [canActiveModal, isModalOpen, isSidebarOpen]);
**suggestion (non-blocking):** Redundant space after semicolon

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +        // <section className="product-detail section">
**suggestion:** Too much commented code. If is not needed, please remove.

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +// .image-gallery-image {
**suggestion:** Ccommented code. If is not needed, please remove.

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/stories/20-Product.stories.js
> +    Alt: "Sectional"
**suggestion:** Change property to lower case

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
>          min-height: 630px;
**suggestion (non-blocking):** Please change to rem

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +    margin-bottom: 10px;
**suggestion (non-blocking):** Please change to rem

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +    background-color: #fff;
**suggestion (non-blocking):** Please use color variable

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +@media only screen and (min-width: $desktop) {
**suggestion (non-blocking):** You can move this to line: 154 for desktop-product-gallery

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
**suggestion:** Redundant empty line

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +        //         <Sidebar
**suggestion:** Recover other functions <-It is the most important

2023-08-04 11:49 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
>  import { ExpandMore, ExpandLess } from "@mui/icons-material"
**suggestion:** If something is not used, remove import

2023-08-04 11:57 UTC, SebaKas21 requested changes

2023-08-04 11:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                    <div className="product-detail__gallery-column__desktop-product-image" key={index}>
**suggestion:** Missing lazy-loading

2023-08-04 11:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                                <ResponsiveImage sources={image.sources} imageSrc={image.Src} imageAlt={image.Alt}/>
**suggestion:** Missing lazy-loading

2023-08-08 10:57 UTC, SebaKas21 requested changes

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +    const [showMoreImg, setShowMoreImg] = useState(false);
**suggestion:** give full function names, example: showMoreImages and setShowMoreImages

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +    const handleShowMoreImg = () => {
**suggestion:** give full function names

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                                <button variant="outlined" className="product-detail__gallery-column__desktop-more-product-images__button-more-less" onClick={handleShowMoreImg}>Zobacz
**suggestion:** Use Button component from MUI library and make more readable code

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                                        <div className="product-detail__gallery-column__mobile-product-image">
**suggestion:** Move this className to lazyLoad and remove redundant div

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                        <div className="product-detail__gallery-column__desktop-product-image" key={index}>
**suggestion:** Move this className to lazyLoad and remove redundant div

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                {props.images.length > 6 &&
**suggestion:** check if photos are added. Take a look on line 147 or 172

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                                <button variant="outlined" className="product-detail__gallery-column__desktop-more-product-images__button-more-less" onClick={handleShowMoreImg}>Zobacz
**suggestion:** Use Button component from MUI library and make more readable code

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +        padding: 0px;
**suggestion:** Use 0 instead of 0px;

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +                font-size: 15px;
**suggestion:** Use rem instead of px;

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                <div className="product-detail__head columns is-tablet">
**suggestion (non-blocking):** I think we can remove it

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                                <button variant="outlined" className="product-detail__gallery-column__desktop-more-product-images__button-more-less" onClick={handleShowMoreImg}>Zobacz
**suggestion (non-blocking):** I think we can minimize the class names

2023-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +    &__arrow:disabled {
**suggestion (non-blocking):** I think we can move this to &__arrow

2023-08-09 11:55 UTC, SebaKas21 requested changes

2023-08-09 11:55 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                                    <ResponsiveImage sources={image.sources} imageSrc={image.src} imageAlt={image.alt} />
**suggestion:** paramete imageSrc is wrong passed. Should be image.imageSrc instead of image.src

2023-08-09 11:55 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                            <ResponsiveImage sources={image.sources} imageSrc={image.src} imageAlt={image.alt} />
**suggestion:** paramete imageSrc is wrong passed. Should be image.imageSrc instead of image.src

2023-08-09 11:55 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +        display: none !important;
**suggestion (non-blocking):** Please try without !important

2023-08-09 11:55 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +            display: block !important;
**suggestion (non-blocking):** Please try without !important

2023-08-09 11:55 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +            display: none !important;
**suggestion (non-blocking):** Please try without !important

2023-08-09 12:00 UTC, SebaKas21 commented
Hi @PiotrZaranek, you are on the right track 👍

2023-08-16 06:04 UTC, SebaKas21 requested changes

2023-08-16 06:04 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +.splide {
**suggestion (non-blocking):** Let's try add to .product-detail

2023-08-16 06:04 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductImageModal/ImageModal.js
> +
**suggestion:** Missing propTypes. Let's look on ProductDetail line 327

2023-08-16 06:04 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductImageModal/ImageModal.js
> +                                        <LazyLoad offset={LazyLoadConstants.defaultOffset()} className="image-modal__image" key={index}>
**suggestion (non-blocking):** Too much tabs

2023-08-16 09:19 UTC, SebaKas21 approved these changes
Hi @PiotrZaranek,

In my opinion your work is well done, but we should wait for on the final decision @dawiddworak88

2023-08-16 09:29 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Shared/ViewModels/Images/ImageViewModel.cs
> +        public string ImageSrc { get; set; }
**suggestion:** Missing ImageAlt in BE

2023-08-17 12:38 UTC, SebaKas21 approved these changes
Nice 👍

2023-08-18 09:31 UTC, SebaKas21 requested changes
Hi @PiotrZaranek

There is no check if there are more than one image, 
if there is only one, it should be displayed in full width

![obraz](https://github.com/dawiddworak88/Giuru/assets/93117743/ad96a589-4990-476c-96a6-5c4fc79534aa)

2023-08-19 17:02 UTC, dawiddworak88 approved these changes

2023-08-19 17:02 UTC, dawiddworak88 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                            {props.images.map((image, index) => {
**suggestion:** Please add a check whether images exist because if there are no images added the the product yet, the whole page will crash:

{props.images && props.images.length &&

2023-08-19 17:02 UTC, dawiddworak88 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +                                slidesPerView={1}
**suggestion (non-blocking):** please move these values to constants and give them descriptive names, let's avoid magic strings. Please, ask @SebaKas21 for hints about it

2023-08-19 17:02 UTC, dawiddworak88 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +        // <section className="product-detail section">
**suggestion:** please remove all the code commented out completely. We use git and we can always find a history

2023-08-19 17:02 UTC, dawiddworak88 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.scss
> +            flex-basis: 47%;
**question:** Where is the number 47% coming from?

2023-08-19 17:02 UTC, dawiddworak88 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ModelBuilders/Products/ProductDetailModelBuilder.cs
> +                    var imageViewModel = new ImageViewModel()
**suggestion:** () is redundant, please replace with:
var imageViewModel = new ImageViewModel
{
...
}

2023-08-19 17:02 UTC, dawiddworak88 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ModelBuilders/Products/ProductDetailModelBuilder.cs
> +                        Sources = new List<SourceViewModel>()
**suggestion:** remove redundant ()

2023-08-19 17:02 UTC, dawiddworak88 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductImageModal/ImageModal.js
> +            console.log(index)
**suggestion:** please remove all console.log

2023-08-19 17:02 UTC, dawiddworak88 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductImageModal/ImageModal.js
> +    const splideRef = useRef();
**suggestion:** is useRef critical here? Can't it be avoided? It should be possible

2023-08-19 17:02 UTC, dawiddworak88 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> -import ImageGallery from "react-image-gallery";
**question and suggestion:** is the "react-image-gallery" used anywhere after removing it here? If not, let's remove it completely from dependencies (packages.json)

2023-08-19 17:02 UTC, dawiddworak88 commented on fe/projects/AspNetCore/src/areas/Products/components/ProductDetail/ProductDetail.js
> +    const [images, setImages] = useState(props.images ? props.images.slice(0, 6) : []);
**suggestion:** please move '6' to constants and give it meaningful name. We should avoid 'magic strings' in code

2023-08-19 17:03 UTC, merged