Add stock button
dawiddworak88/Giuru pull request #372
Opened 2024-07-30 14:59 UTC by PiotrZaranek

2024-08-06 12:56 UTC, SebaKas21 requested changes
Hi @PiotrZaranek 

I see this solution a bit differently.

I would create a dedicated endpoint in buyer.web in the Orders area that will fetch product suggestions based on the searchTerm property. Once it finds products, you will search for them in inventory-api by SKU list. Then you create a dedicated model that will contain the information: ProductName, ProductSku, StockQuantity – assigning the quantity from the stock. This will avoid unnecessary modifications and you will be able to easily display and check the "stock" button. 

If the user doesn't want a product from the stock, he will be able to uncheck it before adding it to the cart, unlike the current solution.

I would do the calculations in NewOrderForm component. This way we don't modify the basket-api, which is not necessary for us.

2024-08-06 12:56 UTC, SebaKas21 commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +    FormControlLabel
**suggestion (non-blocking):** Move to line nr 12

2024-08-06 12:56 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Orders/ApiControllers/BasketsApiController.cs
> +            var basket = await _basketRepository.SaveAsync(token, language, id, items);
**suggestion (non-blocking):** if id is not used out of SaveAsync method, you can use directly Guid.Parse(reqCookie)

2024-08-06 12:56 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Orders/Services/BasketItems/BasketItemsService.cs
> +                        if (productOnStock.AvailableQuantity > quantity)
**question** what about outlet quantity? how to calculate it?

2024-08-08 10:53 UTC, SebaKas21 requested changes

2024-08-08 10:53 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Orders/ApiRequestModels/BasketItemRequestModel.cs
> +        public bool IsFromStock { get; set; }
**suggestion:** it is redundant

2024-08-08 10:53 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Orders/ModelBuilders/OrderFormModelBuilder.cs
> +                GetSuggestionsUrl = _linkGenerator.GetPathByAction("GetProductOrderSuggestion", "ProductsApi", new { Area = "Products", culture = CultureInfo.CurrentUICulture.Name }),
**suggestion: (non-blocking)** you should move this to OrdersApi

2024-08-08 10:53 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Orders/DomainModels/BasketItem.cs
> +        public bool IsFromStock { get; set; }
**suggestion:** Never used

2024-08-08 10:53 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +                    suggestion.StockQuantity = onStockProduct.AvailableQuantity ?? 0;
**suggestion:** ?? 0 is reduntant

2024-08-08 10:53 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Orders/ApiRequestModels/BasketItemRequestModel.cs
> +        public bool IsFromStock { get; set; }
**suggestion:** Never used

2024-08-08 10:53 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Orders/DomainModels/BasketItem.cs
> +        public bool IsFromStock { get; set; }
**suggestion:** Never used

2024-08-08 10:53 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Orders/ModelBuilders/OrderFormModelBuilder.cs
> +                GetSuggestionsUrl = _linkGenerator.GetPathByAction("GetProductOrderSuggestion", "ProductsApi", new { Area = "Products", culture = CultureInfo.CurrentUICulture.Name }),
**suggestion:** Move this to OrdersApi

2024-08-08 10:53 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Orders/components/NewOrderForm/NewOrderForm.js
> +                            setIsStock(false);
**suggestion:** this is redundant

2024-08-08 10:53 UTC, SebaKas21 commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +                            setIsStock(false);
**suggestion:** this is redundant

2024-08-08 10:53 UTC, SebaKas21 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/OrderResources.en.resx
> +    <value>From the warehouse</value>
**suggestion (non-blocking):** What you think about: From stock?

2024-08-08 10:57 UTC, SebaKas21 requested changes

2024-08-08 10:57 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Orders/components/NewOrderForm/NewOrderForm.js
> +                            <div className="column is-2 is-flex is-align-items-flex-end">
**suggestion:** Checkbox should be displayed only when selected product is from stock

2024-08-08 10:57 UTC, SebaKas21 commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +                            <div className="column is-2 is-flex is-align-items-flex-end">
**suggestion:** Checkbox should be displayed only when selected product is from stock

2024-08-08 11:01 UTC, SebaKas21 commented on fe/projects/AspNetCore/src/areas/Orders/components/NewOrderForm/NewOrderForm.js
> +            moreInfo,
**suggestion:** redundant comma

2024-08-08 11:04 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +            List<ProductOrderSuggestionResponseModel> suggestions = new List<ProductOrderSuggestionResponseModel>();
**suggestion:** use var instead of list declaration

2024-08-08 11:04 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +            List<ProductOrderSuggestionResponseModel> suggestions = new List<ProductOrderSuggestionResponseModel>();
**suggestion:** use var instead of list declaration

2024-08-08 11:09 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +            var onStockProducts = await _inventoryRepository.GetInventoryProductsAsync(
**suggestion:** it will be more optimal to get products from the warehouse that come from suggestions - use products.select(x => x.Id);

2024-08-08 11:10 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +            var onStockProducts = await _inventoryRepository.GetAvailbleProductsInventory(language, pageIndex, itemsPerPage, token);
**suggestion:** it will be more optimal to get products from the warehouse that come from suggestions - use products.select(x => x.Id);

2024-08-08 11:11 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +            var onStockProducts = await _inventoryRepository.GetInventoryProductsAsync(
**suggestion:** it will be more optimal to get products from the warehouse that come from suggestions - use products.select(x => x.Id);

2025-01-23 13:17 UTC, SebaKas21 requested changes
Hi @PiotrZaranek 

If there is something unclear in my suggestions, let me know, we will talk about it

I also have a question about what about products ordered via a file? In my opinion, it should also be automatically from stock

2025-01-23 13:17 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ApiResponseModels/ProductQuantitiesResponseModel.cs
> +        public double? StockQuantity { get; set; } = 0;
**suggestion** If you remove the nullable from double you won't have to assign a value because the default value of double is 0

2025-01-23 13:17 UTC, SebaKas21 commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +        return suggestion.name;
**suggestion** Please revert to suggestion with sku information

2025-01-23 13:17 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +        public async Task<IActionResult> GetProductsQuantities(Guid id)
**suggestion** This method in my opinion is redundant because information about stock and outlet items should retrieve from the server during seraching suggestions instead of making additional request on frontend. Use GetSuggestion method from ProductsApiController and extend with required functionality - i mean getting information about quantities, new response model for this method.

Stocks and outlet items should be retrieving by list of skus from the products suggestions

2025-01-23 13:17 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Inventory/Repositories/Outlets/OutletRepository.cs
> +                EndpointAddress = $"{_settings.Value.InventoryUrl}{ApiConstants.Outlet.OutletApiEndpoint}/product/{id}"
**suggestion** If you want stay with this methods i want suggest create new ApiConstants definition - GetOutletProductApiEndpoint instead OutletApiEndpoint

2025-01-23 13:17 UTC, SebaKas21 commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +    const setMaxStockOutletQuantity = (response, sku) => {
**suggestion** You can make it in an easier way to do this, but it depends on whether you decide to follow my previous suggestion.

2025-01-23 20:27 UTC, PiotrZaranek commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ApiResponseModels/ProductQuantitiesResponseModel.cs
> +        public double? StockQuantity { get; set; } = 0;
If I change the property type to double in the ProductQuantitiesResponseModel, I need to update the code in ProductsApiController as follows:

```cs
responseModel.StockQuantity = inventory.AvailableQuantity ?? 0;
```

> Is inventory.AvailableQuantity of type double?

2025-01-23 20:43 UTC, PiotrZaranek commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +        return suggestion.name;
This is the result when I revert my changes:

![image](https://github.com/user-attachments/assets/50f40b8a-24b7-4b50-b978-fb48f51d2382)

`suggestion.name` has value like this: "Anton (An_02)"

Snippet of code from backend:

![image](https://github.com/user-attachments/assets/6e2edc41-0036-4751-a579-5303d5ebf29d)

2025-01-23 21:00 UTC, PiotrZaranek commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +        public async Task<IActionResult> GetProductsQuantities(Guid id)
We discussed this problem and came to the conclusion together that the current implementation is correct because the InventoryApi does not have endpoints to retrieve InventorySum and OutletSum by a list of SKUs in our controllers. We only have endpoints to retrieve a single InventorySum and OutletSum by ID and SKU.

2025-01-26 09:22 UTC, dawiddworak88 requested changes
Hi @PiotrZaranek, let's address the comments as a priority first. We're close to merge this PR.

2025-01-26 09:22 UTC, dawiddworak88 commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +    const [maxStock, setMaxStock] = useState(0);
**suggestion:** the maxStock and maxOutlet should be injected via props from the be and not use state

2025-01-26 09:22 UTC, dawiddworak88 commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +    const setMaxStockOutletQuantity = (response, sku) => {
**suggestion:** to be completely removed, it should be injected from the be and there should be no business logic in the frontend

2025-01-26 09:22 UTC, dawiddworak88 commented on fe/projects/Seller.Portal/src/areas/Orders/components/OrderForm/OrderForm.js
> +        return suggestion.name;
**suggestion:** let's revert this change, changes in suggestions are out of scope for this task

2025-01-26 09:22 UTC, dawiddworak88 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/OrderResources.pl.resx
> -  <data name="sh_clientNameLabel" xml:space="preserve">
**suggestion:** changes to this file are reduntant and the file shouldn't be listed here, let's revert it

2025-01-26 09:22 UTC, dawiddworak88 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +        public async Task<IActionResult> GetProductsQuantities(Guid id)
**suggestion (non-blocking):** let's rename to GetProductQuantities (no s)

2025-01-26 09:22 UTC, dawiddworak88 commented on be/src/Project/Web/Buyer/Buyer.Web/Program.cs
>                  DataCenter = new LogzioDataCenter
**suggestion:** this file shouldn't be listed here at all, please revert

2025-01-26 09:22 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Orders/ModelBuilders/OrderFormModelBuilder.cs
> +                DefaultItemsPerPage = Constants.DefaultItemsPerPage,
**question:** is there already MaximalLabel in global resources already?

2025-01-26 09:22 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +        public async Task<IActionResult> GetProductsQuantities(Guid id)
**suggestion:** Let's extend the existing InventoryApi endpoint to return InventorySum and OutletSum as well

2025-01-27 11:13 UTC, PiotrZaranek commented on be/src/Project/Web/Seller/Seller.Web/Areas/Orders/ModelBuilders/OrderFormModelBuilder.cs
> +                DefaultItemsPerPage = Constants.DefaultItemsPerPage,
Yes, there is

![image](https://github.com/user-attachments/assets/439e216a-a169-48e6-86a4-4823bf667a5e)

2025-01-31 07:50 UTC, SebaKas21 requested changes

2025-01-31 07:50 UTC, SebaKas21 commented on be/src/Project/Services/Inventory/Inventory.Api/v1/Controllers/InventoryController.cs
> +        [Route("product/ids/{ids}")]
**suggestion:** I would left the only products in endpoint and passed the ids as a query

2025-01-31 07:50 UTC, SebaKas21 commented on be/src/Project/Services/Inventory/Inventory.Api/v1/Controllers/OutletController.cs
> +        [Route("product/ids/{ids}")]
**suggestion:** I would left the only products in endpoint and passed the ids as a query

2025-01-31 07:50 UTC, SebaKas21 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +        public async Task<IActionResult> GetProductsQuantities(string searchTerm, int pageIndex, bool? hasPrimaryProduct, int itemsPerPage)
**suggestion:** it can be simplified

Example:
```cs
var products = await _productsRepository.GetProductsAsync(
                token,
                language,
                searchTerm,
                hasPrimaryProduct,
                null,
                pageIndex,
                itemsPerPage,
                null);

if (products.Data.Any())
{
var inventories = await _inventoryRepository.GetAvailbleProductsByProductIdsAsync(
                    token,
                    language,
                    products .Data.Select(x => x.Id));

                var outlets = await _outletRepository.GetOutletProductsByProductsIdAsync(
                    token,
                    language,
                    products.Data.Select(x => x.Id));

return StatusCode((int)HttpStatusCode.OK, products.Data.Select(x => new ProductQuantitiesResponseModel{
}
Id = x.Id,
                 Sku = x.Sku,
                 Name = x.Name,
                 Images = x.Images,
                 StockQuantity = inventories.FirstOrDefault(x => x.ProductId == product.Id)?.AvailableQuantity ?? 0;
                 OutletQuantity = outlets .FirstOrDefault(x => x.ProductId == product.Id)?.AvailableQuantity ?? 0;
));
}
```

2025-01-31 07:50 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Products/ApiControllers/ProductsApiController.cs
> +        public async Task<IActionResult> GetProductsQuantities(string searchTerm, bool? hasPrimaryProduct, int pageIndex, int itemsPerPage)
**suggestion** this can also be simplified

2025-02-09 16:59 UTC, dawiddworak88 requested changes
Hi @PiotrZaranek, only a few very small suggestions, we're almost there. I'd appreciate having a look at them and we'll try to deploy it with @SebaKas21 on Tuesday. I'd also appreciate testing import of order items from Excel file (@SebaKas21 probably has a template), whether it works correctly 🎖️

2025-02-09 16:59 UTC, dawiddworak88 commented on be/src/Project/Web/Buyer/Buyer.Web/Areas/Products/ApiResponseModels/ProductQuantitiesResponseModel.cs
> +    public class ProductQuantitiesResponseModel : Product
**suggestion:** the response models mustn't inherit from domain model. Let's duplicate properties or inherit from another response model

2025-02-09 16:59 UTC, dawiddworak88 commented on be/src/Project/Services/Inventory/Inventory.Api/v1/Controllers/OutletController.cs
> +        /// Gets a products outles by products ids.
**suggestion (non-blocking):** typo - outlets

2025-02-09 16:59 UTC, dawiddworak88 commented on be/src/Project/Services/Inventory/Inventory.Api/v1/Controllers/OutletController.cs
> +        /// <returns>The list of products outles.</returns>
**suggestion (non-blocking):** typo - outlets

2025-02-10 10:00 UTC, dawiddworak88 approved these changes

2025-02-10 10:13 UTC, SebaKas21 approved these changes

2025-02-10 10:13 UTC, merged