Order cancellation button
dawiddworak88/Giuru pull request #39
Opened 2022-04-13 10:57 UTC by SebaKas21

I added buttons below other components, please look and give me feedback :)

2022-04-13 18:08 UTC, dawiddworak88 requested changes

2022-04-13 18:08 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Orders/ApiControllers/OrderStatusApiController.cs
> +            var orderStatusId = await this.ordersRepository.SaveOrderStatusAsync(token, language, model.OrderId, OrdersConstants.OrderStatuses.CancelId);
**suggestion:** Please add check if the order state is in new. If not, throw a custom exception with a meaningful message that only newly created orders can be cancelled.

2022-04-13 18:08 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Orders/components/EditOrderForm/EditOrderForm.js
> +                    <div className="mt-5">
suggestion: Please add logic to show the button only for orders with an order state new. It makes no sense to provoke users with this button for orders that are already in progress, closed, etc.

2022-04-25 19:02 UTC, dawiddworak88 commented
@SebaKas21 , could you merge develop to this feature branch as well?

2022-05-20 06:24 UTC, SebaKas21 commented
@dawiddworak88  Can we merge?

2022-10-10 17:17 UTC, dawiddworak88 requested changes
Hi @SebaKas21 , we need to extend it. The cancel button should be also added to each order item to add a possibility to cancel every order item. The cancellation button on the order should display a modal window with a warning that it will cancel all order items. Thereafter the order items should be cancelled and the order at the end.

2022-10-11 17:01 UTC, dawiddworak88 approved these changes
Merci 👍

2022-10-11 17:01 UTC, merged