Search in Orders by Client Order Number
dawiddworak88/Giuru pull request #40
Opened 2022-04-13 11:10 UTC by SebaKas21

2022-04-13 18:02 UTC, dawiddworak88 requested changes

2022-04-13 18:02 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/Services/OrdersService.cs
> +                orders = orders.Where(x => x.SellerId == model.OrganisationId.Value || x.OrderItems.Any(y => y.ExternalReference.StartsWith(model.SearchTerm)) || x.Id.ToString() == model.SearchTerm);
**suggestion:** Please add ToLowercaseInvariant() to ignore the captial and lowercase in search.

2022-04-13 18:02 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/Services/OrdersService.cs
> +                orders = orders.Where(x => x.ClientName.StartsWith(model.SearchTerm) || x.OrderItems.Any(y => y.ExternalReference.StartsWith(model.SearchTerm)) || x.Id.ToString() == model.SearchTerm)
suggestion: Please add ToLowercaseInvariant() to ignore the captial and lowercase in search.

2022-04-14 07:01 UTC, SebaKas21 commented
@dawiddworak88 

Now is okey?

2022-04-15 16:17 UTC, dawiddworak88 approved these changes

2022-04-15 16:17 UTC, dawiddworak88 commented on be/src/Project/Services/Ordering/Ordering.Api/Services/OrdersService.cs
> +                orders = orders.Where(x => x.ClientName.ToLower().StartsWith(model.SearchTerm.ToLower())
@SebaKas21 , now it's truly case insensitive. When order item has an external reference "ORD_01" and user searches for "ord", the right results are retrieved.

2022-04-15 16:17 UTC, merged