Fix placing orders and sending order confirmation email
dawiddworak88/Giuru pull request #409
Opened 2024-11-05 19:09 UTC by PiotrZaranek

2024-11-06 08:12 UTC, SebaKas21 requested changes

2024-11-06 08:12 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Clients/ModelBuilders/ClientFormModelBuilder.cs
> +                        var approvals = await _approvalsRepository.GetAsync(componentModel.Token, componentModel.Language, null, Constants.DefaultPageIndex, Constants.DefaultItemsPerPage, null);
**suggestion:**  Avoid duplicate repository calls, Reduce redundant assignments and minimize nesting 

code suggestion:
```cs
if (approvals is not null)
{
    var userApprovals = await _userApprovalsRepository.GetAsync(
        componentModel.Token,
        componentModel.Language,
        Guid.Parse(user.Id)
    );

    var approvalsList = approvals.Data.OrEmptyIfNull().Select(x => new ApprovalViewModel
    {
        Id = x.Id,
        Name = x.Name,
        ApprovalDate = null,
        IsApproved = false
    }).ToList();

    foreach (var approval in approvalsList)
    {
        var userApproval = userApprovals.FirstOrDefault(x => x.ApprovalId == approval.Id);
        if (userApproval is not null)
        {
            approval.IsApproved = true;
            approval.ApprovalDate = userApproval.CreatedDate;
        }
    }

    viewModel.ClientApprovals = approvalsList;
}

```

2024-11-06 08:35 UTC, dawiddworak88 approved these changes

2024-11-07 07:20 UTC, SebaKas21 approved these changes

2024-11-07 07:25 UTC, merged