Created Warehouse&Inventory pages/components
dawiddworak88/Giuru pull request #58
Opened 2021-11-04 09:56 UTC by SebaKas21

2021-11-10 07:42 UTC, dawiddworak88 requested changes

2021-11-10 07:42 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Inventory/components/InventoryAddForm/InventoryAddForm.js
> +    const HandleAddItemInventory = (e) => {
**suggestion:** Use consistent names for methods "handleAddItemInventory"

2021-11-10 07:42 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Inventory/components/InventoryAddForm/InventoryAddForm.js
> +    const {warehouse, product, quantity, showBackToInventoryListButton} = formData;
**suggestion (non-blocking):** Add space after brackets { warehouse

2021-11-10 07:42 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Inventory/components/InventoryAddForm/InventoryAddForm.js
> +                                    onChange={handleChange}
**suggestion (non-blocking):** Move ">": up

2021-11-10 07:42 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Inventory/components/InventoryAddForm/InventoryAddForm.js
> +};
**suggestion:** Add missing props like warehouses: PropTypes.array

2021-11-10 07:42 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Inventory/components/InventoryAddForm/InventoryAddForm.js
> +    products: PropTypes.object.isRequired,
**suggestion:** products: PropTypes.array.isRequired

2021-11-10 07:42 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Products/components/ProductForm/ProductForm.js
> +
**suggestion (non-blocking):** Remove redundant new line

2021-11-10 07:42 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Warehouse/components/NewWarehouse/NewWarehouseForm.js
> +        warehouseName: props.warehouseName ? props.warehouseName : "",
**suggestion (non-blocking):** Use short names like "name" instead of "warehouseName"

2021-11-10 07:42 UTC, dawiddworak88 commented
"Box" icon for inventory
"Server" icon for warehouse
Replace "Add" with "New inventory item" oraz "New warehouse"
Replace "Warehouse" with "Warehouses" on Warehouse Page
Warehouse location is filled along with Warehouse name
Use "Save" word for save
Add price and stock to product page (Figma and ask Szymon plus sales)
Run "npm run build-fe" and fix errors
Replace "New order" with "Order"
Replace form handling with "useForm"

Visual Studio 2022
.NET 6

2021-11-11 17:06 UTC, dawiddworak88 requested changes
Hi Sebastian,

pull your branch to get all the latest changes :)

Cheers,

2021-11-11 18:56 UTC, dawiddworak88 requested changes
Hi Sebastian,

I already resolved conflicts. Please have a look at my comment regarding the three new fields on inventory form :)

Cheers and see you in the afternoon,
Dawid

2021-11-11 18:56 UTC, dawiddworak88 commented on fe/src/project/Seller.Portal/areas/Inventory/components/InventoryAddForm/InventoryAddForm.js
> +                            <TextField
**suggestion:** Please add three more fields: available quantity (number text field, mandatory), restockableInDays (number text field) and expected delivery date  (have a look at date picker field used on Add New Order form)

2021-11-12 09:00 UTC, SebaKas21 commented on fe/src/project/Seller.Portal/areas/Inventory/components/InventoryAddForm/InventoryAddForm.js
> +                            <TextField
What should be required in this form?

2021-11-12 14:57 UTC, merged