Outlet integration
dawiddworak88/Giuru pull request #7
Opened 2022-02-09 14:47 UTC by SebaKas21

2022-02-16 21:23 UTC, dawiddworak88 requested changes
I've only started review of outlet but you can already start working on the first remarks once you're happy with placing orders. I'll try to find more time tomorrow, so that you can work on it next week.

2022-02-16 21:23 UTC, dawiddworak88 commented on be/src/Project/Services/Inventory/Inventory.Api/Infrastructure/Entities/Outlet.cs
> +        public Guid? ProductId { get; set; }
**suggestion:** nullable Guid makes no sense with required attribute. It should be:
[Required] 
public Guid ProductId { get; set; }

2022-02-16 21:23 UTC, dawiddworak88 commented on be/src/Project/Services/Inventory/Inventory.Api/IntegrationEventsHandlers/UpdatedProductIntegrationEventHandler.cs
> +                await this.outletService.UpdateOutletProduct(@event.ProductId, @event.ProductName, @event.ProductSku);
**suggestion:** it should be in a separate Event and EventHandler

2022-02-16 21:23 UTC, dawiddworak88 commented on be/src/Project/Services/Inventory/Inventory.Api/Services/Outlets/IOutletService.cs
> +        Task UpdateOutletProduct(Guid? ProductId, string ProductName, string ProductSku);
**suggestion:** correct English is UpdateProductOutlet

2022-02-16 21:23 UTC, dawiddworak88 commented on be/src/Project/Services/Inventory/Inventory.Api/Services/Outlets/OutletService.cs
> +        private readonly IStringLocalizer inventortLocalizer;
**suggestion:** typo, should be inventoryLocalizer

2022-02-17 09:13 UTC, SebaKas21 commented on be/src/Project/Services/Inventory/Inventory.Api/IntegrationEventsHandlers/UpdatedProductIntegrationEventHandler.cs
> +                await this.outletService.UpdateOutletProduct(@event.ProductId, @event.ProductName, @event.ProductSku);
@dawiddworak88  Why? I understand to make separate handler but is it sens to copy the same code?

2022-04-02 19:01 UTC, dawiddworak88 requested changes
1. Please merge develop branch to this branch and resolve conflicts
2. Make all the quantity fields as wide as the Quantity field and double check texts are not overlapping inputs:
![image](https://user-images.githubusercontent.com/7514974/161397204-f7b35670-ddc7-42ed-afb3-a3e7d7cf0aaa.png)
3. Add validation with meaningful error message when none of the quanitty fields is filled up. At the moment following happens:
![image](https://user-images.githubusercontent.com/7514974/161397300-6b22749d-243a-4b62-9aab-6f33f6c55a11.png)
4. At the moment I'm able to add more items to basket then available (from stock or outlet). It makes no sense. It should be checked client-side and a meaniful validation message should be displayed.
5. It shouldn't be able to enter quantity less than 0 (like -5, or -10)
6. External Reference and More Info should be null in DB if not provided
![image](https://user-images.githubusercontent.com/7514974/161397849-f8e46c2c-2b4f-41b4-bba7-2148d1bec306.png)
7. Quantity should be preset to "1", except when adding from Stock (there should Stock quantity be preset to "1") or Outlet (there should Outlet quantity be set to 1)

2022-04-20 20:23 UTC, dawiddworak88 requested changes
Hi @SebaKas21 ,

seems to be almost perfect. Could you please add some space (push more air) between SKU and product name? 

![image](https://user-images.githubusercontent.com/7514974/164316340-ac6f56a4-7626-45d8-9719-edf458b56d3d.png)

Cheers,

2022-04-20 20:25 UTC, dawiddworak88 commented
@SebaKas21:  I'd also appreciate if you could merge develop branch to this branch and resolve conflicts. I'd be thankful if you could smoke test it once again thereafter (conflicts are usually not easy to predict consequences).

2022-04-22 12:53 UTC, dawiddworak88 approved these changes

2022-04-22 12:53 UTC, merged