Renamed Client Managers to Client Account Managers
dawiddworak88/Giuru pull request #96
Opened 2022-06-13 09:20 UTC by SebaKas21

2022-06-13 19:23 UTC, dawiddworak88 requested changes

2022-06-13 19:23 UTC, dawiddworak88 commented on be/src/Infrastructure/Localization/Foundation.Localization/Resources/ClientResources.en.resx
> +    <value>Client account managers</value>
**suggestion:** there are probably some more labels to have a look at:

![image](https://user-images.githubusercontent.com/7514974/173429145-70b653de-052c-47d4-bb60-f99c12f4e5c9.png)

2022-06-14 08:28 UTC, SebaKas21 commented
Hi @dawiddworak88 

The only place I haven't changed is the menu.

![obraz](https://user-images.githubusercontent.com/93117743/173530862-4ece4b46-f578-4650-ad3f-a9ecb9c3fd32.png)

2022-06-15 20:29 UTC, dawiddworak88 approved these changes
Perfect 👍

2022-06-15 20:29 UTC, merged