Renemed Medias to MediaItems
dawiddworak88/Giuru pull request #98
Opened 2022-06-20 11:52 UTC by SebaKas21

2022-06-20 18:44 UTC, dawiddworak88 requested changes

2022-06-20 18:44 UTC, dawiddworak88 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Media/ApiRequestModels/UploadMediaItemRequestModel.cs
> +    public class UploadMediaItemRequestModel : RequestModelBase
**suggestion:** it's too much of a change. We should only get rid of the 'Medias'. I'd leave everything else as it was.

2022-06-21 11:01 UTC, SebaKas21 commented on be/src/Project/Web/Seller/Seller.Web/Areas/Media/ApiRequestModels/UploadMediaItemRequestModel.cs
> +    public class UploadMediaItemRequestModel : RequestModelBase
Okey

2022-06-21 12:00 UTC, SebaKas21 commented
Hi @dawiddworak88 

Now will be okey

2022-06-22 06:37 UTC, dawiddworak88 approved these changes

2022-06-22 06:37 UTC, merged